export const GET_CINEMA_LIST = "GET_CINEMA_LIST";
export const GET_SHOWTIMES_FILM = "GET_SHOWTIMES_FILM";
export const GET_SHOWTIMES_FILM_CINEMA = "GET_SHOWTIMES_FILM_CINEMA";
export const POST_NEW_SHOWTIME = "POST_NEW_SHOWTIME";
